zones:
- name: speed_bump
  type: speed_bump
  vertices:
  - - 2.02
    - -6.94
  - - 0.77
    - -6.94
  - - 0.77
    - -5.69
  - - 5.32
    - -5.69
  - - 5.32
    - -6.94
  - - 4.82
    - -6.94
  - - 4.82
    - -6.79
  - - 2.27
    - -6.79
  - - 2.27
    - -6.99
  - - 4.82
    - -6.99
  - - 4.82
    - -8.99
  - - 2.02
    - -8.99
